version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: recipe-postgres
    environment:
      POSTGRES_DB: recipedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: recipe-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=recipedb
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - db

volumes:
  postgres_data: